
export interface Topic {
    id: string;
    title: string;
    description?: string;
    subtopics?: string[];
}

export interface ClassSyllabus {
    grade: number;
    topics: Topic[];
}

export const mathSyllabus: Record<number, Topic[]> = {
    1: [
        { id: '1-1', title: 'Numbers up to 20', description: 'Counting, reading, and writing numbers 1-20' },
        { id: '1-2', title: 'Addition up to 20', description: 'Basic addition within 20' },
        { id: '1-3', title: 'Subtraction up to 20', description: 'Basic subtraction within 20' },
        { id: '1-4', title: 'Shapes and Patterns', description: 'Identifying basic 2D shapes and repeating patterns' },
        { id: '1-5', title: 'Measurement', description: 'Length, weight, and capacity (non-standard units)' },
        { id: '1-6', title: 'Data Handling', description: 'Simple data collection and interpretation' },
    ],
    2: [
        { id: '2-1', title: 'Numbers up to 100', description: 'Place value, standard form' },
        { id: '2-2', title: 'Addition and Subtraction (2-digit)', description: 'With carrying and borrowing' },
        { id: '2-3', title: 'Introduction to Multiplication', description: 'Repeated addition, groups' },
        { id: '2-4', title: 'Shapes and Solids', description: '3D shapes properties' },
        { id: '2-5', title: 'Measurement', description: 'Standard units (cm, m, g, kg, l)' },
        { id: '2-6', title: 'Time and Calendar', description: 'Reading clock, days, months' },
    ],
    3: [
        { id: '3-1', title: 'Numbers up to 1000', description: '4-digit numbers, expanded form' },
        { id: '3-2', title: 'Addition and Subtraction (3-digit)', description: 'Word problems' },
        { id: '3-3', title: 'Multiplication Tables', description: 'Facts 1-10' },
        { id: '3-4', title: 'Division Introduction', description: 'Sharing equally, grouping' },
        { id: '3-5', title: 'Fractions', description: 'Halves, thirds, quarters' },
        { id: '3-6', title: 'money', description: 'Currency, making change' },
        { id: '3-7', title: 'Measurement', description: 'Length (m, km), Weight, Capacity' },
        { id: '3-8', title: 'Geometry', description: 'Point, Line, Ray, Angles introduction' },
    ],
    4: [
        { id: '4-1', title: 'Large Numbers', description: 'Up to 6 digits' },
        { id: '4-2', title: 'Operations on Large Numbers', description: 'Addition, Subtraction, Multiplication, Division' },
        { id: '4-3', title: 'Factors and Multiples', description: 'HCF, LCM basics' },
        { id: '4-4', title: 'Fractions', description: 'Types, equivalent fractions, basic operations' },
        { id: '4-5', title: 'Decimals', description: 'Introduction, tenths, hundredths' },
        { id: '4-6', title: 'Geometry', description: 'Angles, Types of triangles, Circles' },
        { id: '4-7', title: 'Perimeter and Area', description: 'Squares and rectangles' },
    ],
    5: [
        { id: '5-1', title: 'Large Numbers', description: 'Indian and International system, rounding' },
        { id: '5-2', title: 'Operations', description: 'With large numbers, Bodmas rule basics' },
        { id: '5-3', title: 'Factors and Multiples', description: 'HCF, LCM word problems' },
        { id: '5-4', title: 'Fractions and Decimals', description: 'All operations, conversion' },
        { id: '5-5', title: 'Percentage', description: 'Introduction, simple problems' },
        { id: '5-6', title: 'Geometry', description: 'Lines and angles detailed, symmetry' },
        { id: '5-7', title: 'Perimeter, Area and Volume', description: 'Rectangles, squares, cubes, cuboids' },
        { id: '5-8', title: 'Data Handling', description: 'Bar graphs, pictographs' },
    ],
    6: [
        { id: '6-1', title: 'Knowing Our Numbers', description: 'Estimation, whole numbers' },
        { id: '6-2', title: 'Playing with Numbers', description: 'Tests for divisibility' },
        { id: '6-3', title: 'Basic Geometrical Ideas', description: 'Curves, Polygons' },
        { id: '6-4', title: 'Integers', description: 'Negative numbers, number line' },
        { id: '6-5', title: 'Fractions and Decimals', description: 'Comparing, ordering' },
        { id: '6-6', title: 'Data Handling', description: 'Recording data, bar graphs' },
        { id: '6-7', title: 'Mensuration', description: 'Perimeter and area of composite shapes' },
        { id: '6-8', title: 'Algebra', description: 'Introduction to variables' },
        { id: '6-9', title: 'Ratio and Proportion', description: 'Idea of ratio, unitary method' },
    ],
    7: [
        { id: '7-1', title: 'Integers', description: 'Properties of addition, multiplication' },
        { id: '7-2', title: 'Fractions and Decimals', description: 'Multiplication and division' },
        { id: '7-3', title: 'Data Handling', description: 'Mean, median, mode, range' },
        { id: '7-4', title: 'Simple Equations', description: 'Setting up and solving' },
        { id: '7-5', title: 'Lines and Angles', description: 'Pairs of angles, traversal' },
        { id: '7-6', title: 'The Triangle and its Properties', description: 'Medians, altitudes, angle sum' },
        { id: '7-7', title: 'Congruence of Triangles', description: 'Criteria for congruence' },
        { id: '7-8', title: 'Comparing Quantities', description: 'Ratio, percentage, profit/loss, simple interest' },
        { id: '7-9', title: 'Rational Numbers', description: 'Introduction and operations' },
        { id: '7-10', title: 'Perimeter and Area', description: 'Parallelograms, triangles, circles' },
        { id: '7-11', title: 'Algebraic Expressions', description: 'Terms, factors, coefficients' },
        { id: '7-12', title: 'Exponents and Powers', description: 'Laws of exponents' },
    ],
    8: [
        { id: '8-1', title: 'Rational Numbers', description: 'Properties, representation on number line' },
        { id: '8-2', title: 'Linear Equations in One Variable', description: 'Solving equations' },
        { id: '8-3', title: 'Understanding Quadrilaterals', description: 'Polygons, types of quadrilaterals' },
        { id: '8-4', title: 'Data Handling', description: 'Pie charts, probability' },
        { id: '8-5', title: 'Squares and Square Roots', description: 'Finding roots' },
        { id: '8-6', title: 'Cubes and Cube Roots', description: 'Finding roots' },
        { id: '8-7', title: 'Comparing Quantities', description: 'Compound Interest, Tax, Discount' },
        { id: '8-8', title: 'Algebraic Expressions and Identities', description: 'Ops, standard identities' },
        { id: '8-9', title: 'Mensuration', description: 'Trapezium, general quadrilaterals, cylinder surface/vol' },
        { id: '8-10', title: 'Exponents and Powers', description: 'Negative exponents' },
        { id: '8-11', title: 'Direct and Inverse Proportions', description: 'Solving problems' },
        { id: '8-12', title: 'Factorisation', description: 'Numbers and algebraic expressions' },
        { id: '8-13', title: 'Introduction to Graphs', description: 'Linear graphs' },
    ],
    9: [
        { id: '9-1', title: 'Number Systems', description: 'Irrational numbers, real numbers' },
        { id: '9-2', title: 'Polynomials', description: 'Remainder theorem, factorization' },
        { id: '9-3', title: 'Coordinate Geometry', description: 'Cartesian system' },
        { id: '9-4', title: 'Linear Equations in Two Variables', description: 'Graphing lines' },
        { id: '9-5', title: 'Introduction to Euclid\'s Geometry', description: 'Axioms and postulates' },
        { id: '9-6', title: 'Lines and Angles', description: 'Basic terms, intersecting lines' },
        { id: '9-7', title: 'Triangles', description: 'Congruence, inequalities' },
        { id: '9-8', title: 'Quadrilaterals', description: 'Properties of parallelograms' },
        { id: '9-9', title: 'Circles', description: 'Chords, arcs, cyclic quadrilaterals' },
        { id: '9-10', title: 'Heron\'s Formula', description: 'Area of triangles' },
        { id: '9-11', title: 'Surface Areas and Volumes', description: 'Cube, cuboid, sphere, cylinder, cone' },
        { id: '9-12', title: 'Statistics', description: 'Data presentation, central tendency' },
        { id: '9-13', title: 'Probability', description: 'Empirical probability' },
    ],
    10: [
        { id: '10-1', title: 'Real Numbers', description: 'Fundamental Theorem of Arithmetic' },
        { id: '10-2', title: 'Polynomials', description: 'Zeros, division algorithm' },
        { id: '10-3', title: 'Pair of Linear Equations in Two Variables', description: 'Graphical, substitution, elimination methods' },
        { id: '10-4', title: 'Quadratic Equations', description: 'Solution by factorization, formula' },
        { id: '10-5', title: 'Arithmetic Progressions', description: 'nth term, sum of first n terms' },
        { id: '10-6', title: 'Triangles', description: 'Similarity, BPT, Pythagoras theorem' },
        { id: '10-7', title: 'Coordinate Geometry', description: 'Distance formula, Section formula' },
        { id: '10-8', title: 'Introduction to Trigonometry', description: 'Ratios, identities' },
        { id: '10-9', title: 'Some Applications of Trigonometry', description: 'Heights and distances' },
        { id: '10-10', title: 'Circles', description: 'Tangents' },
        { id: '10-11', title: 'Areas Related to Circles', description: 'Sector and segment' },
        { id: '10-12', title: 'Surface Areas and Volumes', description: 'Combinations of solids' },
        { id: '10-13', title: 'Statistics', description: 'Mean, median, mode of grouped data' },
        { id: '10-14', title: 'Probability', description: 'Theoretical approach' },
    ],
    11: [
        { id: '11-1', title: 'Sets', description: 'Types, operations, Venn diagrams' },
        { id: '11-2', title: 'Relations and Functions', description: 'Cartesian product, domain, range' },
        { id: '11-3', title: 'Trigonometric Functions', description: 'Sign, graphs, identities' },
        { id: '11-4', title: 'Principle of Mathematical Induction', description: 'Process of proof' },
        { id: '11-5', title: 'Complex Numbers and Quadratic Equations', description: 'Algebra of complex numbers' },
        { id: '11-6', title: 'Linear Inequalities', description: 'Solution in one and two variables' },
        { id: '11-7', title: 'Permutations and Combinations', description: 'Fundamental principle of counting' },
        { id: '11-8', title: 'Binomial Theorem', description: 'Positive integral index' },
        { id: '11-9', title: 'Sequence and Series', description: 'AP, GP, relationships' },
        { id: '11-10', title: 'Straight Lines', description: 'Slope, forms of equations' },
        { id: '11-11', title: 'Conic Sections', description: 'Circle, parabola, ellipse, hyperbola' },
        { id: '11-12', title: 'Introduction to Three Dimensional Geometry', description: 'Coordinates, distance formula' },
        { id: '11-13', title: 'Limits and Derivatives', description: 'Intro to calculus' },
        { id: '11-14', title: 'Mathematical Reasoning', description: 'Statements, logic' },
        { id: '11-15', title: 'Statistics', description: 'Measures of dispersion' },
        { id: '11-16', title: 'Probability', description: 'Axiomatic approach' },
    ],
    12: [
        { id: '12-1', title: 'Relations and Functions', description: 'Types of relations, inverse functions' },
        { id: '12-2', title: 'Inverse Trigonometric Functions', description: 'Domain, range, principal value' },
        { id: '12-3', title: 'Matrices', description: 'Types, operations, transpose, inverse' },
        { id: '12-4', title: 'Determinants', description: 'Properties, applications (area of triangle)' },
        { id: '12-5', title: 'Continuity and Differentiability', description: 'Chain rule, derivatives of various functions' },
        { id: '12-6', title: 'Applications of Derivatives', description: 'Rate of change, tangents, excessive/minima' },
        { id: '12-7', title: 'Integrals', description: 'Indefinite and definite integrals' },
        { id: '12-8', title: 'Application of Integrals', description: 'Area under curves' },
        { id: '12-9', title: 'Differential Equations', description: 'Order, degree, solutions' },
        { id: '12-10', title: 'Vector Algebra', description: 'Vectors, dot and cross products' },
        { id: '12-11', title: 'Three Dimensional Geometry', description: 'Direction cosines, lines, planes' },
        { id: '12-12', title: 'Linear Programming', description: 'Optimization problems' },
        { id: '12-13', title: 'Probability', description: 'Conditional probability, Bayes theorem' },
    ],
};
